# Generated by Django 3.2.8 on 2021-10-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Айди юзера')),
                ('create_date', models.DateTimeField(verbose_name='Время создания')),
                ('status', models.CharField(max_length=255, verbose_name='Статус чата')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTypes',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Айди типа')),
                ('name', models.CharField(max_length=256, verbose_name='Название типа')),
            ],
        ),
        migrations.CreateModel(
            name='WebUsers',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Айди юзера')),
                ('user_name', models.CharField(max_length=256, verbose_name='Юзернейм')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='', verbose_name='Аватарка')),
            ],
        ),
        migrations.CreateModel(
            name='WebMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(verbose_name='Время отправки')),
                ('content', models.TextField(verbose_name='контент')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_data.chats', verbose_name='Чат')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_data.webusers', verbose_name='Юзер')),
                ('message_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_data.messagetypes', verbose_name='Тип сообщения')),
            ],
        ),
    ]
