# Generated by Django 3.2.8 on 2021-10-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_data', '0002_updates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='MessageUpdates',
        ),
    ]
