# Generated by Django 3.2.8 on 2021-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_data', '0003_rename_updates_messageupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='webusers',
            name='comment',
            field=models.TextField(default='', verbose_name='Коментарий'),
        ),
    ]
