# Generated by Django 3.2.8 on 2021-11-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_data', '0004_webusers_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestedMessages',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Айди сообщения')),
                ('content', models.TextField(verbose_name='Контент')),
                ('preview', models.CharField(max_length=255, verbose_name='Превью сообщения')),
                ('message_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_data.messagetypes', verbose_name='Тип сообщения')),
            ],
        ),
    ]
